#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

#PKG_NAME:=optee-os
PKG_VERSION:=4.2
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/OpenNuvoton/optee_os_ma35.git

PKG_CPE_ID:=cpe:/o:linaro:op-tee
PKG_SOURCE_DATE:=2025-10-28
PKG_SOURCE_VERSION:=4b165ce31f423b33d743c4b8e7996b85fe8b98f7
PKG_MIRROR_HASH:=d53602ae131bc447a6e90e750412a0269141ef3c0feda65e4046aaac38b6173b

include $(INCLUDE_DIR)/kernel.mk
include $(INCLUDE_DIR)/optee-os.mk
include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/image.mk

define Optee-os/Default
  BUILD_TARGET:=$(BOARD)
  DEPENDS:=@(TARGET_ma35d1||TARGET_ma35d0||TARGET_ma35h0)
endef

define Optee-os/ma35
  NAME:=MA35D1
  PLATFORM:=ma35
endef

OPTEE_TARGETS := ma35

ifeq ($(BOARD),ma35d1)
  OPTEE_MAKE_FLAGS += PLATFORM_FLAVOR=MA35D1 all
else ifeq ($(BOARD),ma35h0)
  OPTEE_MAKE_FLAGS += PLATFORM_FLAVOR=MA35H0 all
else ifeq ($(BOARD),ma35d0)
  OPTEE_MAKE_FLAGS += PLATFORM_FLAVOR=MA35D0 all
endif

$(info PROFILE = $(PROFILE))
ifneq ($(findstring 128m,$(PROFILE)),)
  OPTEE_MAKE_FLAGS += CFG_TZDRAM_START=0x87800000 CFG_SHMEM_START=0x87F00000
else ifneq ($(findstring 256m,$(PROFILE)),)
  OPTEE_MAKE_FLAGS += CFG_TZDRAM_START=0x8F800000 CFG_SHMEM_START=0x8FF00000
else ifneq ($(findstring 512m,$(PROFILE)),)
  OPTEE_MAKE_FLAGS += CFG_TZDRAM_START=0x9F800000 CFG_SHMEM_START=0x9FF00000
else
  OPTEE_MAKE_FLAGS += CFG_TZDRAM_START=0xAF800000 CFG_SHMEM_START=0xAFF00000
endif

define Package/optee-os/install/default
endef

define Build/InstallDev
	touch /tmp/openwrt.boot
	sed -i /^OPTEE_/d /tmp/openwrt.boot
	echo OPTEE_PROFILE=$(PROFILE) >> /tmp/openwrt.boot
	echo OPTEE_TA_DIR=$(PKG_BUILD_DIR)/out/arm-plat-ma35/export-ta_arm64 >> /tmp/openwrt.boot

	$(INSTALL_DATA) $(PKG_BUILD_DIR)/out/arm-plat-ma35/core/tee.bin $(STAGING_DIR_IMAGE)/tee.bin
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/out/arm-plat-ma35/core/tee-pager_v2.bin $(STAGING_DIR_IMAGE)/tee-pager_v2.bin
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/out/arm-plat-ma35/core/tee-header_v2.bin $(STAGING_DIR_IMAGE)/tee-header_v2.bin
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/out/arm-plat-ma35/core/tee-pageable_v2.bin $(STAGING_DIR_IMAGE)/tee-pageable_v2.bin

	$(INSTALL_DIR) $(1)/lib/optee_armtz/
	$(INSTALL_DATA) $(PKG_BUILD_DIR)/out/arm-plat-ma35/export-ta_arm64/ta/*.ta $(1)/lib/optee_armtz/
endef

$(eval $(call BuildPackage/Optee-os))
